### ISSUE TITLE
ParCool! problem

### ISSUE THREAD

**Issue by DoctorNis** [Xing-C/Classic-and-simple-status-bars#4]
Description: Unexpected error

java.lang.NoSuchFieldError: UseHungerBarInstead
	at com.alrex.parcool.client.hud.impl.StaminaHUDController.handler$eaj000$classicandsimplestatusbars$registerThirstOverlay(StaminaHUDController.java:521) ~[ParCool-1.20.1-3.2.1.2-R.jar%23643!/:1.20.1-3.2.1.2-R] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:classicandsimplestatusbars.mixin.json:ParCoolMixin from mod classicandsimplestatusbars,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.alrex.parcool.client.hud.impl.StaminaHUDController.render(StaminaHUDController.java) ~[ParCool-1.20.1-3.2.1.2-R.jar%23643!/:1.20.1-3.2.1.2-R] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:classicandsimplestatusbars.mixin.json:ParCoolMixin from mod classicandsimplestatusbars,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-47.2.17-universal.jar%23735!/:?] {re:mixin,re:classloading,pl:mixin:APP:immersiveui.mixins.json:GooeyMixin from mod immersiveui,pl:mixin:APP:mixins.oculus.json:gui.MixinForgeGui from mod oculus,pl:mixin:APP:connectormod.mixins.json:hud.ForgeGuiMixin from mod connectormod,pl:mixin:APP:betterf3.forge.mixins.json:ForgeGuiMixin from mod betterf3,pl:mixin:APP:apoli.mixins.json:forge.ForgeGuiMixin from mod apoli,pl:mixin:APP:quark.mixins.json:client.ForgeGuiMixin from mod quark,pl:mixin:APP:embeddium.mixins.json:features.render.gui.debug.ForgeGuiMixin from mod embeddium,pl:mixin:APP:immediatelyfast-forge.mixins.json:hud_batching.MixinForgeGui from mod immediatelyfast,pl:mixin:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23103!/:?] {re:mixin}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.2.17-universal.jar%23735!/:?] {re:mixin,re:classloading,pl:mixin:APP:immersiveui.mixins.json:GooeyMixin from mod immersiveui,pl:mixin:APP:mixins.oculus.json:gui.MixinForgeGui from mod oculus,pl:mixin:APP:connectormod.mixins.json:hud.ForgeGuiMixin from mod connectormod,pl:mixin:APP:betterf3.forge.mixins.json:ForgeGuiMixin from mod betterf3,pl:mixin:APP:apoli.mixins.json:forge.ForgeGuiMixin from mod apoli,pl:mixin:APP:quark.mixins.json:client.ForgeGuiMixin from mod quark,pl:mixin:APP:embeddium.mixins.json:features.render.gui.debug.ForgeGuiMixin from mod embeddium,pl:mixin:APP:immediatelyfast-forge.mixins.json:hud_batching.MixinForgeGui from mod immediatelyfast,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:945) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:vinery-common.mixins.json:GameRendererMixin from mod vinery,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:loot_journal.mixins.json:GameRendererMixin from mod loot_journal,pl:mixin:APP:sleep_tight-common.mixins.json:GameRendererMixin from mod sleep_tight,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin from mod dynamic_fps,pl:mixin:APP:corgilib.mixins.json:client.GameRendererMixin from mod corgilib,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin from mod embeddiumplus,pl:mixin:APP:mixins.satin.client.json:event.GameRendererMixin from mod (unknown),pl:mixin:APP:enhancedvisuals.mixins.json:GameRendererMixin from mod enhancedvisuals,pl:mixin:APP:cameraoverhaul.mixins.json:modern.GameRendererMixin from mod cameraoverhaul,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:bobby.mixins.json:GameRendererMixin from mod bobby,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:panorama_screen-common.mixins.json:GameRendererMixin from mod panorama_screens,pl:mixin:APP:apoli.mixins.json:GameRendererMixin from mod apoli,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin from mod fastload,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes,pl:mixin:APP:owo.mixins.json:shader.GameRendererMixin from mod owo,pl:mixin:APP:accurateblockplacement.mixins.json:GameRendererMixin from mod accurateblockplacement,pl:mixin:APP:crackerslib.mixins.json:MixinGameRendererAccessor from mod crackerslib,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:apugli.mixins.json:client.GameRendererMixin from mod apugli,pl:mixin:APP:apugli.mixins.json:client.accessor.GameRendererAccessor from mod apugli,pl:mixin:APP:apugli.forge.mixins.json:client.GameRendererMixin from mod apugli,pl:mixin:APP:rrls.mixins.json:compat.GameRendererMixin from mod (unknown),pl:mixin:APP:rrls.mixins.json:compat.RendererKeyboardMouseMixin from mod (unknown),pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:APP:forge-badoptimizations.mixins.json:accessor.GameRendererAccessor from mod (unknown),pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.17.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain from mod notenoughcrashes,pl:mixin:APP:mixins.emibridge.json:MainEntrypointMixin from mod connectorextras_emi_bridge,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	ParCool! (parcool), Version: 1.20.1-3.2.1.2-R
		Issue tracker URL: https://github.com/alRex-U/ParCool/issues
		at TRANSFORMER/parcool@1.20.1-3.2.1.2-R/com.alrex.parcool.client.hud.impl.StaminaHUDController.handler$eaj000$classicandsimplestatusbars$registerThirstOverlay(StaminaHUDController.java:521)

	Classic and simple status bars (classicandsimplestatusbars), Version: 1.0.13
		Mixin class: cn.mcxkly.classicandsimplestatusbars.mixin.ParCoolMixin
		Target: com.alrex.parcool.client.hud.impl.StaminaHUDController
		at TRANSFORMER/parcool@1.20.1-3.2.1.2-R/com.alrex.parcool.client.hud.impl.StaminaHUDController.handler$eaj000$classicandsimplestatusbars$registerThirstOverlay(StaminaHUDController.java:521)
Stacktrace:
	at com.alrex.parcool.client.hud.impl.StaminaHUDController.handler$eaj000$classicandsimplestatusbars$registerThirstOverlay(StaminaHUDController.java:521) ~[ParCool-1.20.1-3.2.1.2-R.jar%23643!/:1.20.1-3.2.1.2-R] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:classicandsimplestatusbars.mixin.json:ParCoolMixin from mod classicandsimplestatusbars,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.alrex.parcool.client.hud.impl.StaminaHUDController.render(StaminaHUDController.java) ~[ParCool-1.20.1-3.2.1.2-R.jar%23643!/:1.20.1-3.2.1.2-R] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:classicandsimplestatusbars.mixin.json:ParCoolMixin from mod classicandsimplestatusbars,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-47.2.17-universal.jar%23735!/:?] {re:mixin,re:classloading,pl:mixin:APP:immersiveui.mixins.json:GooeyMixin from mod immersiveui,pl:mixin:APP:mixins.oculus.json:gui.MixinForgeGui from mod oculus,pl:mixin:APP:connectormod.mixins.json:hud.ForgeGuiMixin from mod connectormod,pl:mixin:APP:betterf3.forge.mixins.json:ForgeGuiMixin from mod betterf3,pl:mixin:APP:apoli.mixins.json:forge.ForgeGuiMixin from mod apoli,pl:mixin:APP:quark.mixins.json:client.ForgeGuiMixin from mod quark,pl:mixin:APP:embeddium.mixins.json:features.render.gui.debug.ForgeGuiMixin from mod embeddium,pl:mixin:APP:immediatelyfast-forge.mixins.json:hud_batching.MixinForgeGui from mod immediatelyfast,pl:mixin:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23103!/:?] {re:mixin}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.2.17-universal.jar%23735!/:?] {re:mixin,re:classloading,pl:mixin:APP:immersiveui.mixins.json:GooeyMixin from mod immersiveui,pl:mixin:APP:mixins.oculus.json:gui.MixinForgeGui from mod oculus,pl:mixin:APP:connectormod.mixins.json:hud.ForgeGuiMixin from mod connectormod,pl:mixin:APP:betterf3.forge.mixins.json:ForgeGuiMixin from mod betterf3,pl:mixin:APP:apoli.mixins.json:forge.ForgeGuiMixin from mod apoli,pl:mixin:APP:quark.mixins.json:client.ForgeGuiMixin from mod quark,pl:mixin:APP:embeddium.mixins.json:features.render.gui.debug.ForgeGuiMixin from mod embeddium,pl:mixin:APP:immediatelyfast-forge.mixins.json:hud_batching.MixinForgeGui from mod immediatelyfast,pl:mixin:A}

2
I also have a problem, the names of the selected items end up in my crosshair

**Comment by Xing-C** [comment]
I have received it, I apologize for only seeing it now. This minor issue has been fixed in a new version, and I will upload an update in the near future.

**Comment by Xing-C** [comment]
A new version has been released on modrinth

**Comment by Xing-C** [comment]
> A new version has been released on modrinth

The second question may not be because of this
